import React, { useState, useEffect } from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

export const DisclaimerModal: React.FC = () => {
  const [isOpen, setIsOpen] = useState(true);
  const [canClose, setCanClose] = useState(false);

  useEffect(() => {
    // Force user to read for at least 2 seconds
    const timer = setTimeout(() => setCanClose(true), 2000);
    return () => clearTimeout(timer);
  }, []);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4">
      <div className="bg-slate-900 border border-red-500/50 rounded-2xl max-w-2xl w-full shadow-2xl shadow-red-900/20 overflow-hidden">
        <div className="bg-red-500/10 p-6 flex items-center gap-4 border-b border-red-500/20">
          <AlertTriangle className="w-10 h-10 text-red-500" />
          <h2 className="text-2xl font-bold text-white">Critical Medical Disclaimer</h2>
        </div>
        
        <div className="p-8 space-y-6 text-slate-300 leading-relaxed">
          <p className="text-lg font-medium text-white">
            This application ("Bio-Integrator AI") is a <span className="text-red-400">demonstration prototype</span> for educational purposes only.
          </p>
          
          <ul className="list-disc pl-5 space-y-2">
            <li>It is <strong>NOT</strong> a medical device and has not been evaluated by the FDA.</li>
            <li>It does <strong>NOT</strong> provide medical diagnoses, treatment, or professional advice.</li>
            <li>All data analysis is generated by an AI Language Model which can hallucinate or provide incorrect information.</li>
            <li>Do not rely on this system for health decisions. Always consult a qualified healthcare professional.</li>
          </ul>

          <div className="bg-slate-800 p-4 rounded-lg border border-slate-700">
            <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-2">Data Privacy Notice</h3>
            <p className="text-sm">
              This demo runs locally in your browser. However, when you click "Analyze", data is sent to the Google Gemini API for processing. Do not upload real PII (Personally Identifiable Information) alongside PHI (Protected Health Information).
            </p>
          </div>
        </div>

        <div className="p-6 bg-slate-950 flex justify-end">
          <button
            onClick={() => canClose && setIsOpen(false)}
            disabled={!canClose}
            className={`flex items-center gap-2 px-6 py-3 rounded-lg font-semibold transition-all ${
              canClose 
                ? 'bg-red-600 hover:bg-red-700 text-white shadow-lg shadow-red-900/40 cursor-pointer' 
                : 'bg-slate-800 text-slate-500 cursor-not-allowed'
            }`}
          >
            <ShieldCheck className="w-5 h-5" />
            {canClose ? "I Acknowledge & Accept Risks" : "Please Read Carefully..."}
          </button>
        </div>
      </div>
    </div>
  );
};